package com.gridgain.sales.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Customer definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class Customer implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for customername. */
    private String customername;

    /** Value for contactlastname. */
    private String contactlastname;

    /** Value for contactfirstname. */
    private String contactfirstname;

    /** Value for phone. */
    private String phone;

    /** Value for addressline1. */
    private String addressline1;

    /** Value for addressline2. */
    private String addressline2;

    /** Value for city. */
    private String city;

    /** Value for state. */
    private String state;

    /** Value for postalcode. */
    private String postalcode;

    /** Value for country. */
    private String country;

    /** Value for salesrepemployeenumber. */
    private Integer salesrepemployeenumber;

    /** Value for creditlimit. */
    private BigDecimal creditlimit;

    /** Empty constructor. **/
    public Customer() {
        // No-op.
    }

    /** Full constructor. **/
    public Customer(String customername,
        String contactlastname,
        String contactfirstname,
        String phone,
        String addressline1,
        String addressline2,
        String city,
        String state,
        String postalcode,
        String country,
        Integer salesrepemployeenumber,
        BigDecimal creditlimit) {
        this.customername = customername;
        this.contactlastname = contactlastname;
        this.contactfirstname = contactfirstname;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.city = city;
        this.state = state;
        this.postalcode = postalcode;
        this.country = country;
        this.salesrepemployeenumber = salesrepemployeenumber;
        this.creditlimit = creditlimit;
    }

    /**
     * Gets customername
     * 
     * @return Value for customername.
     **/
    public String getCustomername() {
        return customername;
    }

    /**
     * Sets customername
     * 
     * @param customername New value for customername.
     **/
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * Gets contactlastname
     * 
     * @return Value for contactlastname.
     **/
    public String getContactlastname() {
        return contactlastname;
    }

    /**
     * Sets contactlastname
     * 
     * @param contactlastname New value for contactlastname.
     **/
    public void setContactlastname(String contactlastname) {
        this.contactlastname = contactlastname;
    }

    /**
     * Gets contactfirstname
     * 
     * @return Value for contactfirstname.
     **/
    public String getContactfirstname() {
        return contactfirstname;
    }

    /**
     * Sets contactfirstname
     * 
     * @param contactfirstname New value for contactfirstname.
     **/
    public void setContactfirstname(String contactfirstname) {
        this.contactfirstname = contactfirstname;
    }

    /**
     * Gets phone
     * 
     * @return Value for phone.
     **/
    public String getPhone() {
        return phone;
    }

    /**
     * Sets phone
     * 
     * @param phone New value for phone.
     **/
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets addressline1
     * 
     * @return Value for addressline1.
     **/
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * Sets addressline1
     * 
     * @param addressline1 New value for addressline1.
     **/
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * Gets addressline2
     * 
     * @return Value for addressline2.
     **/
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * Sets addressline2
     * 
     * @param addressline2 New value for addressline2.
     **/
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    /**
     * Gets city
     * 
     * @return Value for city.
     **/
    public String getCity() {
        return city;
    }

    /**
     * Sets city
     * 
     * @param city New value for city.
     **/
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets state
     * 
     * @return Value for state.
     **/
    public String getState() {
        return state;
    }

    /**
     * Sets state
     * 
     * @param state New value for state.
     **/
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Gets postalcode
     * 
     * @return Value for postalcode.
     **/
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * Sets postalcode
     * 
     * @param postalcode New value for postalcode.
     **/
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * Gets country
     * 
     * @return Value for country.
     **/
    public String getCountry() {
        return country;
    }

    /**
     * Sets country
     * 
     * @param country New value for country.
     **/
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Gets salesrepemployeenumber
     * 
     * @return Value for salesrepemployeenumber.
     **/
    public Integer getSalesrepemployeenumber() {
        return salesrepemployeenumber;
    }

    /**
     * Sets salesrepemployeenumber
     * 
     * @param salesrepemployeenumber New value for salesrepemployeenumber.
     **/
    public void setSalesrepemployeenumber(Integer salesrepemployeenumber) {
        this.salesrepemployeenumber = salesrepemployeenumber;
    }

    /**
     * Gets creditlimit
     * 
     * @return Value for creditlimit.
     **/
    public BigDecimal getCreditlimit() {
        return creditlimit;
    }

    /**
     * Sets creditlimit
     * 
     * @param creditlimit New value for creditlimit.
     **/
    public void setCreditlimit(BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Customer))
            return false;
        
        Customer that = (Customer)o;

        if (customername != null ? !customername.equals(that.customername) : that.customername != null)
            return false;
        

        if (contactlastname != null ? !contactlastname.equals(that.contactlastname) : that.contactlastname != null)
            return false;
        

        if (contactfirstname != null ? !contactfirstname.equals(that.contactfirstname) : that.contactfirstname != null)
            return false;
        

        if (phone != null ? !phone.equals(that.phone) : that.phone != null)
            return false;
        

        if (addressline1 != null ? !addressline1.equals(that.addressline1) : that.addressline1 != null)
            return false;
        

        if (addressline2 != null ? !addressline2.equals(that.addressline2) : that.addressline2 != null)
            return false;
        

        if (city != null ? !city.equals(that.city) : that.city != null)
            return false;
        

        if (state != null ? !state.equals(that.state) : that.state != null)
            return false;
        

        if (postalcode != null ? !postalcode.equals(that.postalcode) : that.postalcode != null)
            return false;
        

        if (country != null ? !country.equals(that.country) : that.country != null)
            return false;
        

        if (salesrepemployeenumber != null ? !salesrepemployeenumber.equals(that.salesrepemployeenumber) : that.salesrepemployeenumber != null)
            return false;
        

        if (creditlimit != null ? !creditlimit.equals(that.creditlimit) : that.creditlimit != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = customername != null ? customername.hashCode() : 0;

        res = 31 * res + (contactlastname != null ? contactlastname.hashCode() : 0);

        res = 31 * res + (contactfirstname != null ? contactfirstname.hashCode() : 0);

        res = 31 * res + (phone != null ? phone.hashCode() : 0);

        res = 31 * res + (addressline1 != null ? addressline1.hashCode() : 0);

        res = 31 * res + (addressline2 != null ? addressline2.hashCode() : 0);

        res = 31 * res + (city != null ? city.hashCode() : 0);

        res = 31 * res + (state != null ? state.hashCode() : 0);

        res = 31 * res + (postalcode != null ? postalcode.hashCode() : 0);

        res = 31 * res + (country != null ? country.hashCode() : 0);

        res = 31 * res + (salesrepemployeenumber != null ? salesrepemployeenumber.hashCode() : 0);

        res = 31 * res + (creditlimit != null ? creditlimit.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Customer [" + 
            "customername=" + customername + ", " + 
            "contactlastname=" + contactlastname + ", " + 
            "contactfirstname=" + contactfirstname + ", " + 
            "phone=" + phone + ", " + 
            "addressline1=" + addressline1 + ", " + 
            "addressline2=" + addressline2 + ", " + 
            "city=" + city + ", " + 
            "state=" + state + ", " + 
            "postalcode=" + postalcode + ", " + 
            "country=" + country + ", " + 
            "salesrepemployeenumber=" + salesrepemployeenumber + ", " + 
            "creditlimit=" + creditlimit +
        "]";
    }
}