package com.gridgain.sales.model;

import java.io.Serializable;

/**
 * Employee definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class Employee implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for lastname. */
    private String lastname;

    /** Value for firstname. */
    private String firstname;

    /** Value for extension. */
    private String extension;

    /** Value for email. */
    private String email;

    /** Value for officecode. */
    private String officecode;

    /** Value for reportsto. */
    private Integer reportsto;

    /** Value for jobtitle. */
    private String jobtitle;

    /** Empty constructor. **/
    public Employee() {
        // No-op.
    }

    /** Full constructor. **/
    public Employee(String lastname,
        String firstname,
        String extension,
        String email,
        String officecode,
        Integer reportsto,
        String jobtitle) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.extension = extension;
        this.email = email;
        this.officecode = officecode;
        this.reportsto = reportsto;
        this.jobtitle = jobtitle;
    }

    /**
     * Gets lastname
     * 
     * @return Value for lastname.
     **/
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets lastname
     * 
     * @param lastname New value for lastname.
     **/
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Gets firstname
     * 
     * @return Value for firstname.
     **/
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets firstname
     * 
     * @param firstname New value for firstname.
     **/
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Gets extension
     * 
     * @return Value for extension.
     **/
    public String getExtension() {
        return extension;
    }

    /**
     * Sets extension
     * 
     * @param extension New value for extension.
     **/
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Gets email
     * 
     * @return Value for email.
     **/
    public String getEmail() {
        return email;
    }

    /**
     * Sets email
     * 
     * @param email New value for email.
     **/
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets officecode
     * 
     * @return Value for officecode.
     **/
    public String getOfficecode() {
        return officecode;
    }

    /**
     * Sets officecode
     * 
     * @param officecode New value for officecode.
     **/
    public void setOfficecode(String officecode) {
        this.officecode = officecode;
    }

    /**
     * Gets reportsto
     * 
     * @return Value for reportsto.
     **/
    public Integer getReportsto() {
        return reportsto;
    }

    /**
     * Sets reportsto
     * 
     * @param reportsto New value for reportsto.
     **/
    public void setReportsto(Integer reportsto) {
        this.reportsto = reportsto;
    }

    /**
     * Gets jobtitle
     * 
     * @return Value for jobtitle.
     **/
    public String getJobtitle() {
        return jobtitle;
    }

    /**
     * Sets jobtitle
     * 
     * @param jobtitle New value for jobtitle.
     **/
    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Employee))
            return false;
        
        Employee that = (Employee)o;

        if (lastname != null ? !lastname.equals(that.lastname) : that.lastname != null)
            return false;
        

        if (firstname != null ? !firstname.equals(that.firstname) : that.firstname != null)
            return false;
        

        if (extension != null ? !extension.equals(that.extension) : that.extension != null)
            return false;
        

        if (email != null ? !email.equals(that.email) : that.email != null)
            return false;
        

        if (officecode != null ? !officecode.equals(that.officecode) : that.officecode != null)
            return false;
        

        if (reportsto != null ? !reportsto.equals(that.reportsto) : that.reportsto != null)
            return false;
        

        if (jobtitle != null ? !jobtitle.equals(that.jobtitle) : that.jobtitle != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = lastname != null ? lastname.hashCode() : 0;

        res = 31 * res + (firstname != null ? firstname.hashCode() : 0);

        res = 31 * res + (extension != null ? extension.hashCode() : 0);

        res = 31 * res + (email != null ? email.hashCode() : 0);

        res = 31 * res + (officecode != null ? officecode.hashCode() : 0);

        res = 31 * res + (reportsto != null ? reportsto.hashCode() : 0);

        res = 31 * res + (jobtitle != null ? jobtitle.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Employee [" + 
            "lastname=" + lastname + ", " + 
            "firstname=" + firstname + ", " + 
            "extension=" + extension + ", " + 
            "email=" + email + ", " + 
            "officecode=" + officecode + ", " + 
            "reportsto=" + reportsto + ", " + 
            "jobtitle=" + jobtitle +
        "]";
    }
}