package com.gridgain.sales.model;

import java.io.Serializable;

/**
 * Office definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class Office implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for city. */
    private String city;

    /** Value for phone. */
    private String phone;

    /** Value for addressline1. */
    private String addressline1;

    /** Value for addressline2. */
    private String addressline2;

    /** Value for state. */
    private String state;

    /** Value for country. */
    private String country;

    /** Value for postalcode. */
    private String postalcode;

    /** Value for territory. */
    private String territory;

    /** Empty constructor. **/
    public Office() {
        // No-op.
    }

    /** Full constructor. **/
    public Office(String city,
        String phone,
        String addressline1,
        String addressline2,
        String state,
        String country,
        String postalcode,
        String territory) {
        this.city = city;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.state = state;
        this.country = country;
        this.postalcode = postalcode;
        this.territory = territory;
    }

    /**
     * Gets city
     * 
     * @return Value for city.
     **/
    public String getCity() {
        return city;
    }

    /**
     * Sets city
     * 
     * @param city New value for city.
     **/
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Gets phone
     * 
     * @return Value for phone.
     **/
    public String getPhone() {
        return phone;
    }

    /**
     * Sets phone
     * 
     * @param phone New value for phone.
     **/
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets addressline1
     * 
     * @return Value for addressline1.
     **/
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * Sets addressline1
     * 
     * @param addressline1 New value for addressline1.
     **/
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * Gets addressline2
     * 
     * @return Value for addressline2.
     **/
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * Sets addressline2
     * 
     * @param addressline2 New value for addressline2.
     **/
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    /**
     * Gets state
     * 
     * @return Value for state.
     **/
    public String getState() {
        return state;
    }

    /**
     * Sets state
     * 
     * @param state New value for state.
     **/
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Gets country
     * 
     * @return Value for country.
     **/
    public String getCountry() {
        return country;
    }

    /**
     * Sets country
     * 
     * @param country New value for country.
     **/
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Gets postalcode
     * 
     * @return Value for postalcode.
     **/
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * Sets postalcode
     * 
     * @param postalcode New value for postalcode.
     **/
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * Gets territory
     * 
     * @return Value for territory.
     **/
    public String getTerritory() {
        return territory;
    }

    /**
     * Sets territory
     * 
     * @param territory New value for territory.
     **/
    public void setTerritory(String territory) {
        this.territory = territory;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Office))
            return false;
        
        Office that = (Office)o;

        if (city != null ? !city.equals(that.city) : that.city != null)
            return false;
        

        if (phone != null ? !phone.equals(that.phone) : that.phone != null)
            return false;
        

        if (addressline1 != null ? !addressline1.equals(that.addressline1) : that.addressline1 != null)
            return false;
        

        if (addressline2 != null ? !addressline2.equals(that.addressline2) : that.addressline2 != null)
            return false;
        

        if (state != null ? !state.equals(that.state) : that.state != null)
            return false;
        

        if (country != null ? !country.equals(that.country) : that.country != null)
            return false;
        

        if (postalcode != null ? !postalcode.equals(that.postalcode) : that.postalcode != null)
            return false;
        

        if (territory != null ? !territory.equals(that.territory) : that.territory != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = city != null ? city.hashCode() : 0;

        res = 31 * res + (phone != null ? phone.hashCode() : 0);

        res = 31 * res + (addressline1 != null ? addressline1.hashCode() : 0);

        res = 31 * res + (addressline2 != null ? addressline2.hashCode() : 0);

        res = 31 * res + (state != null ? state.hashCode() : 0);

        res = 31 * res + (country != null ? country.hashCode() : 0);

        res = 31 * res + (postalcode != null ? postalcode.hashCode() : 0);

        res = 31 * res + (territory != null ? territory.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Office [" + 
            "city=" + city + ", " + 
            "phone=" + phone + ", " + 
            "addressline1=" + addressline1 + ", " + 
            "addressline2=" + addressline2 + ", " + 
            "state=" + state + ", " + 
            "country=" + country + ", " + 
            "postalcode=" + postalcode + ", " + 
            "territory=" + territory +
        "]";
    }
}