package com.gridgain.sales.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * OrderDetail definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class OrderDetail implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for quantityordered. */
    private int quantityordered;

    /** Value for priceeach. */
    private BigDecimal priceeach;

    /** Value for orderlinenumber. */
    private short orderlinenumber;

    /** Empty constructor. **/
    public OrderDetail() {
        // No-op.
    }

    /** Full constructor. **/
    public OrderDetail(int quantityordered,
        BigDecimal priceeach,
        short orderlinenumber) {
        this.quantityordered = quantityordered;
        this.priceeach = priceeach;
        this.orderlinenumber = orderlinenumber;
    }

    /**
     * Gets quantityordered
     * 
     * @return Value for quantityordered.
     **/
    public int getQuantityordered() {
        return quantityordered;
    }

    /**
     * Sets quantityordered
     * 
     * @param quantityordered New value for quantityordered.
     **/
    public void setQuantityordered(int quantityordered) {
        this.quantityordered = quantityordered;
    }

    /**
     * Gets priceeach
     * 
     * @return Value for priceeach.
     **/
    public BigDecimal getPriceeach() {
        return priceeach;
    }

    /**
     * Sets priceeach
     * 
     * @param priceeach New value for priceeach.
     **/
    public void setPriceeach(BigDecimal priceeach) {
        this.priceeach = priceeach;
    }

    /**
     * Gets orderlinenumber
     * 
     * @return Value for orderlinenumber.
     **/
    public short getOrderlinenumber() {
        return orderlinenumber;
    }

    /**
     * Sets orderlinenumber
     * 
     * @param orderlinenumber New value for orderlinenumber.
     **/
    public void setOrderlinenumber(short orderlinenumber) {
        this.orderlinenumber = orderlinenumber;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof OrderDetail))
            return false;
        
        OrderDetail that = (OrderDetail)o;

        if (quantityordered != that.quantityordered)
            return false;
        

        if (priceeach != null ? !priceeach.equals(that.priceeach) : that.priceeach != null)
            return false;
        

        if (orderlinenumber != that.orderlinenumber)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = quantityordered;

        res = 31 * res + (priceeach != null ? priceeach.hashCode() : 0);

        res = 31 * res + (int)orderlinenumber;

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "OrderDetail [" + 
            "quantityordered=" + quantityordered + ", " + 
            "priceeach=" + priceeach + ", " + 
            "orderlinenumber=" + orderlinenumber +
        "]";
    }
}