package com.gridgain.sales.model;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Date;
import java.sql.Date;

/**
 * Order definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class Order implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for orderdate. */
    private Date orderdate;

    /** Value for requireddate. */
    private Date requireddate;

    /** Value for shippeddate. */
    private Date shippeddate;

    /** Value for status. */
    private String status;

    /** Value for comments. */
    private String comments;

    /** Value for customernumber. */
    private int customernumber;

    /** Empty constructor. **/
    public Order() {
        // No-op.
    }

    /** Full constructor. **/
    public Order(Date orderdate,
        Date requireddate,
        Date shippeddate,
        String status,
        String comments,
        int customernumber) {
        this.orderdate = orderdate;
        this.requireddate = requireddate;
        this.shippeddate = shippeddate;
        this.status = status;
        this.comments = comments;
        this.customernumber = customernumber;
    }

    /**
     * Gets orderdate
     * 
     * @return Value for orderdate.
     **/
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * Sets orderdate
     * 
     * @param orderdate New value for orderdate.
     **/
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * Gets requireddate
     * 
     * @return Value for requireddate.
     **/
    public Date getRequireddate() {
        return requireddate;
    }

    /**
     * Sets requireddate
     * 
     * @param requireddate New value for requireddate.
     **/
    public void setRequireddate(Date requireddate) {
        this.requireddate = requireddate;
    }

    /**
     * Gets shippeddate
     * 
     * @return Value for shippeddate.
     **/
    public Date getShippeddate() {
        return shippeddate;
    }

    /**
     * Sets shippeddate
     * 
     * @param shippeddate New value for shippeddate.
     **/
    public void setShippeddate(Date shippeddate) {
        this.shippeddate = shippeddate;
    }

    /**
     * Gets status
     * 
     * @return Value for status.
     **/
    public String getStatus() {
        return status;
    }

    /**
     * Sets status
     * 
     * @param status New value for status.
     **/
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets comments
     * 
     * @return Value for comments.
     **/
    public String getComments() {
        return comments;
    }

    /**
     * Sets comments
     * 
     * @param comments New value for comments.
     **/
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * Gets customernumber
     * 
     * @return Value for customernumber.
     **/
    public int getCustomernumber() {
        return customernumber;
    }

    /**
     * Sets customernumber
     * 
     * @param customernumber New value for customernumber.
     **/
    public void setCustomernumber(int customernumber) {
        this.customernumber = customernumber;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Order))
            return false;
        
        Order that = (Order)o;

        if (orderdate != null ? !orderdate.equals(that.orderdate) : that.orderdate != null)
            return false;
        

        if (requireddate != null ? !requireddate.equals(that.requireddate) : that.requireddate != null)
            return false;
        

        if (shippeddate != null ? !shippeddate.equals(that.shippeddate) : that.shippeddate != null)
            return false;
        

        if (status != null ? !status.equals(that.status) : that.status != null)
            return false;
        

        if (comments != null ? !comments.equals(that.comments) : that.comments != null)
            return false;
        

        if (customernumber != that.customernumber)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = orderdate != null ? orderdate.hashCode() : 0;

        res = 31 * res + (requireddate != null ? requireddate.hashCode() : 0);

        res = 31 * res + (shippeddate != null ? shippeddate.hashCode() : 0);

        res = 31 * res + (status != null ? status.hashCode() : 0);

        res = 31 * res + (comments != null ? comments.hashCode() : 0);

        res = 31 * res + (customernumber);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Order [" + 
            "orderdate=" + orderdate + ", " + 
            "requireddate=" + requireddate + ", " + 
            "shippeddate=" + shippeddate + ", " + 
            "status=" + status + ", " + 
            "comments=" + comments + ", " + 
            "customernumber=" + customernumber +
        "]";
    }
}