package com.gridgain.sales.model;

import java.io.Serializable;

/**
 * OrderDetailKey definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class OrderDetailKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for ordernumber. */
    private int ordernumber;

    /** Value for productcode. */
    private String productcode;

    /** Empty constructor. **/
    public OrderDetailKey() {
        // No-op.
    }

    /** Full constructor. **/
    public OrderDetailKey(int ordernumber,
        String productcode) {
        this.ordernumber = ordernumber;
        this.productcode = productcode;
    }

    /**
     * Gets ordernumber
     * 
     * @return Value for ordernumber.
     **/
    public int getOrdernumber() {
        return ordernumber;
    }

    /**
     * Sets ordernumber
     * 
     * @param ordernumber New value for ordernumber.
     **/
    public void setOrdernumber(int ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * Gets productcode
     * 
     * @return Value for productcode.
     **/
    public String getProductcode() {
        return productcode;
    }

    /**
     * Sets productcode
     * 
     * @param productcode New value for productcode.
     **/
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof OrderDetailKey))
            return false;
        
        OrderDetailKey that = (OrderDetailKey)o;

        if (ordernumber != that.ordernumber)
            return false;
        

        if (productcode != null ? !productcode.equals(that.productcode) : that.productcode != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = ordernumber;

        res = 31 * res + (productcode != null ? productcode.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "OrderDetailKey [" + 
            "ordernumber=" + ordernumber + ", " + 
            "productcode=" + productcode +
        "]";
    }
}