package com.gridgain.sales.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Product definition.
 * 
 * This file was generated by Ignite Web Console (04/23/2020, 16:26)
 **/
public class Product implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for productname. */
    private String productname;

    /** Value for productline. */
    private String productline;

    /** Value for productscale. */
    private String productscale;

    /** Value for productvendor. */
    private String productvendor;

    /** Value for productdescription. */
    private String productdescription;

    /** Value for quantityinstock. */
    private short quantityinstock;

    /** Value for buyprice. */
    private BigDecimal buyprice;

    /** Value for msrp. */
    private BigDecimal msrp;

    /** Empty constructor. **/
    public Product() {
        // No-op.
    }

    /** Full constructor. **/
    public Product(String productname,
        String productline,
        String productscale,
        String productvendor,
        String productdescription,
        short quantityinstock,
        BigDecimal buyprice,
        BigDecimal msrp) {
        this.productname = productname;
        this.productline = productline;
        this.productscale = productscale;
        this.productvendor = productvendor;
        this.productdescription = productdescription;
        this.quantityinstock = quantityinstock;
        this.buyprice = buyprice;
        this.msrp = msrp;
    }

    /**
     * Gets productname
     * 
     * @return Value for productname.
     **/
    public String getProductname() {
        return productname;
    }

    /**
     * Sets productname
     * 
     * @param productname New value for productname.
     **/
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * Gets productline
     * 
     * @return Value for productline.
     **/
    public String getProductline() {
        return productline;
    }

    /**
     * Sets productline
     * 
     * @param productline New value for productline.
     **/
    public void setProductline(String productline) {
        this.productline = productline;
    }

    /**
     * Gets productscale
     * 
     * @return Value for productscale.
     **/
    public String getProductscale() {
        return productscale;
    }

    /**
     * Sets productscale
     * 
     * @param productscale New value for productscale.
     **/
    public void setProductscale(String productscale) {
        this.productscale = productscale;
    }

    /**
     * Gets productvendor
     * 
     * @return Value for productvendor.
     **/
    public String getProductvendor() {
        return productvendor;
    }

    /**
     * Sets productvendor
     * 
     * @param productvendor New value for productvendor.
     **/
    public void setProductvendor(String productvendor) {
        this.productvendor = productvendor;
    }

    /**
     * Gets productdescription
     * 
     * @return Value for productdescription.
     **/
    public String getProductdescription() {
        return productdescription;
    }

    /**
     * Sets productdescription
     * 
     * @param productdescription New value for productdescription.
     **/
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    /**
     * Gets quantityinstock
     * 
     * @return Value for quantityinstock.
     **/
    public short getQuantityinstock() {
        return quantityinstock;
    }

    /**
     * Sets quantityinstock
     * 
     * @param quantityinstock New value for quantityinstock.
     **/
    public void setQuantityinstock(short quantityinstock) {
        this.quantityinstock = quantityinstock;
    }

    /**
     * Gets buyprice
     * 
     * @return Value for buyprice.
     **/
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * Sets buyprice
     * 
     * @param buyprice New value for buyprice.
     **/
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * Gets msrp
     * 
     * @return Value for msrp.
     **/
    public BigDecimal getMsrp() {
        return msrp;
    }

    /**
     * Sets msrp
     * 
     * @param msrp New value for msrp.
     **/
    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Product))
            return false;
        
        Product that = (Product)o;

        if (productname != null ? !productname.equals(that.productname) : that.productname != null)
            return false;
        

        if (productline != null ? !productline.equals(that.productline) : that.productline != null)
            return false;
        

        if (productscale != null ? !productscale.equals(that.productscale) : that.productscale != null)
            return false;
        

        if (productvendor != null ? !productvendor.equals(that.productvendor) : that.productvendor != null)
            return false;
        

        if (productdescription != null ? !productdescription.equals(that.productdescription) : that.productdescription != null)
            return false;
        

        if (quantityinstock != that.quantityinstock)
            return false;
        

        if (buyprice != null ? !buyprice.equals(that.buyprice) : that.buyprice != null)
            return false;
        

        if (msrp != null ? !msrp.equals(that.msrp) : that.msrp != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = productname != null ? productname.hashCode() : 0;

        res = 31 * res + (productline != null ? productline.hashCode() : 0);

        res = 31 * res + (productscale != null ? productscale.hashCode() : 0);

        res = 31 * res + (productvendor != null ? productvendor.hashCode() : 0);

        res = 31 * res + (productdescription != null ? productdescription.hashCode() : 0);

        res = 31 * res + (int)quantityinstock;

        res = 31 * res + (buyprice != null ? buyprice.hashCode() : 0);

        res = 31 * res + (msrp != null ? msrp.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Product [" + 
            "productname=" + productname + ", " + 
            "productline=" + productline + ", " + 
            "productscale=" + productscale + ", " + 
            "productvendor=" + productvendor + ", " + 
            "productdescription=" + productdescription + ", " + 
            "quantityinstock=" + quantityinstock + ", " + 
            "buyprice=" + buyprice + ", " + 
            "msrp=" + msrp +
        "]";
    }
}