package com.gridgain.sales.load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (04/23/2020, 16:26) **/
public class LoadCachesFromCacheStore {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("sales-client.xml")) {
            ignite.cluster().active(true);

            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: OfficeCache");
            ignite.cache("OfficeCache").loadCache(null); //, "/home/glenn/data/sales/productline.csv");

            System.out.println(">>> Loading cache: ProductLineCache");
            ignite.cache("ProductLineCache").loadCache(null); //, "/home/glenn/data/sales/productline.csv");

            System.out.println(">>> Loading cache: ProductCache");
            ignite.cache("ProductCache").loadCache(null); //, "/home/glenn/data/sales/product.csv");

            System.out.println(">>> Loading cache: EmployeeCache");
            ignite.cache("EmployeeCache").loadCache(null); //, "/home/glenn/data/sales/employee.csv");

            System.out.println(">>> Loading cache: CustomerCache");
            ignite.cache("CustomerCache").loadCache(null); //, "/home/glenn/data/sales/customer.csv");

            System.out.println(">>> Loading cache: OrderCache");
            ignite.cache("OrderCache").loadCache(null); //, "/home/glenn/data/sales/order.csv");

            System.out.println(">>> Loading cache: OrderDetailCache");
            ignite.cache("OrderDetailCache").loadCache(null); //, "/home/glenn/data/sales/orderdetail.csv");

            System.out.println(">>> Loading cache: PaymentCache");
            ignite.cache("PaymentCache").loadCache(null); //, "/home/glenn/data/sales/payment.csv");

            System.out.println(">>> All caches loaded!");
        }
    }
}